project:
  type: website
  output-dir: docs

website:
  title: "Andrew J. Sage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - research.qmd
      - cv.qmd
      - hobbies.qmd


format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

