---
title: "CV"
format: html
editor: visual
---

# COLLEGE FACULTY POSITIONS

**Lawrence University, Appleton, WI**\
Associate Professor of Statistics: 2024-present\
Assistant Professor of Statistics: 2018-2024

# EDUCATION

Iowa State University, Ames, IA\
Degree: Ph.D. in Statistics 2018\
Dissertation Title: Random forest robustness, variable importance and tree aggregation\
Advisors: Ulrike Genschel, Dan Nettleton

Iowa State University, Ames, IA\
Degree: M.S. in Statistics 2015\
Master’s Project: Predicting student retention in STEM: A random forest based approach\
Advisor: Dan Nettleton

Miami University, Oxford, OH\
Degree: M.S. in Mathematics 2013\
Master’s Project: Calculation of cell bounds for contingency tables from rounded conditional frequencies\
Advisor: Stephen Wright

The College of Wooster, Wooster, OH\
Degree: B.A. in Mathematics 2007\
Summa Cum Laude

# TEACHING EXPERIENCE

Lawrence University, Appleton, WI\
Assistant/Associate Professor of Statistics

-   STAT 107: Principles of Statistics: 11 sections (2018-25)\
-   STAT 255: Statistics for Data Science: 10 sections (2020-24)\
-   CMSC/STAT: Data-Scientific Programming: 6 sections (2020-24)\
-   STAT 455: Advanced Statistical Modeling: 5 sections (2021-25)\
-   MATH 340: Probability (previously MATH 240): 3 sections (2018, 22, 25)\
-   STAT 450: Bayesian Statistics: 1 sections (2020)\
-   MATH 430: Statistical Modeling: 1 sections (2019)\
-   FRST 100: First-Year Studies: 2 sections (2019-20)\
-   Advised 21 Chandler Senior Experiences and co-advised 7 others

Iowa State University, Ames, IA\
Graduate teaching assistant, Department of Statistics

-   STAT 231: Probability and Statistics for Engineering S17, F18, S18\
-   STAT 330: Probability and Statistics for Computer Science F16\
-   STAT 104: Introductory Statistics F14\
-   Lab instructor for STAT 421Survey Sampling Techniques S14\

Miami University, Oxford, OH\
Graduate teaching assistant, Department of Mathematics

-   Math 151: Calculus I S13\
-   Math 123: Precalculus F11, S12, F12\

Bloomfield High School, North Bloomfield, OH 2007-11 High school mathematics teacher

Ashtabula County Joint Vocational School, Jefferson, OH 2007-08 High school mathematics summer school teacher

# PEER-REVIEWED PUBLICATIONS

Hilt L.M., Vachhani, S.S., Vaghasia, N.V., Swords, C.M., Sage, A. J. (2025). Brief App-Based Mood Monitoring and Mindfulness Intervention for First-Year College Students: A Randomized Controlled Trial. *Journal of Psychopathology and Behavioral Assessment* 47(1), 1-11.   

Roy, R., Hammerdahl, E., Sage, A. J., & Becker, E. A. (2025). Mating may enhance rapid formation of stable pair bonds in the monogamous California mouse. *Ethology*, e13545. 

Sage, A. J., Liu+, Y., & Sato+, J. (2022). From black box to shining spotlight: Using random forest prediction intervals to illuminate the impact of assumptions in linear regression. The American Statistician, 76(4), 414-429.

Smith, J. G., Sage, A. J., McGlenn+, M., Robbins, J., & Garmon, S. L. (2022). Is Sexual Racism Still Really Racism? Revisiting Callander et al.(2015) in the USA. Archives of Sexual Behavior, 51(6), 3049-3062.

Sage, A.J., Genschel, U., Nettleton, D. (2021). A residual-Based approach to robust random forest regression. Statistics and its Interface. 14(4), 389-402.

Sage, A. J., Cervato, C., Genschel, U., & Ogilvie, C. A. (2021). Combining academics and social engagement: A major-specific early alert method to counter student attrition in science, technology, engineering, and mathematics. Journal of College Student Retention: Research, Theory & Practice, 22(4), 611-626.

Sage, A.J., Genschel, U., Nettleton, D. (2020). Tree aggregation for random forest class probability estimation. Statistical Analysis and Data Mining: The ASA Data Science Journal. 13(2), 134-150.

Sage, A. J., & Wright, S. E. (2016). Obtaining cell counts for contingency tables from rounded conditional frequencies. European Journal of Operational Research, 250(1), 91-100.

+denotes undergraduate student author advised by A.J. Sage

# UNDERGRADUATE RESEARCH 

- Undergraduate research publication co-advised (with Jonathan Lhost): Brickley, D. (2022). The Effect of Academic Performance on Athletic Success in Collegiate Athletic Programs. SIAM Undergraduate Research Online, DOI: 10.1137/22S1491216

- Mentored 12 Lawrence University Summer Research Fellows on 8 projects:\      

    -   Healthy Living Indicators for Neigbhorhoods in the Fox Cities - a community-based project in collaboration with Fox Valley Data Exchange (2025) - 2 students \    
    -    Statistical Algorithms for Ranking Sports Teams (2025) - 2 students \    
    -    Be Well Fox Valley - analysis of data collected in an educational program sponsored by United Ways Fox Cities promoting healthy living, in collaboration with Dr. Mark Jenike (2023-24) - 1 student \    
    -   Connected Community Wellness Screening - analysis of data from wellness screening in Appleton Area Schools, in collaboration with Dr. Lori Hilt (2023) - 1 student \    
    -    Gaining Insight Through Statistical Machine Learning (2022) - 2 students \    
    -    Is Sexual Racism Really Racism, in collaboration with Dr. Jesús Smith (2020) - 1 student      
    -    Visualizing Random Forest Prediction Intervals (2019) - 2 students \    
    -    Shakespeare and Stats (2019) - 1 student \    


# SERVICE

-   Lawrence University Committees
    -   Faculty Committee on University Governance (2024-25 & 2025-26), co-chair (2025-26)
    -   Curriculum Committee (2022-23 & 2023-24)
    -   First-Year Studies Committee (2020-21 & 2021-22)
    -   Internal Review Board (2019-20)
-   Phi Beta Kappa Lawrence University Delta-Gamma Chapter
    -   President (2022-23 & 2023-24)
    -   Vice President (2020-21 & 2021-22)
-   Reviewer for articles in
    -   The American Statistician (2023 & 2024)
    -   Journal of Statistics and Data Science Education (2023 & 2024)
    -   AIMS Mathematics (2022)
    -   PLOS One (2021)
    -   Numeracy (2019)
    -   SIAM Undergraduate Research Online (2018)
-   Judge for Undergraduate Statistics Project Competition (USPROC), Fall 2018, Spring 2019, Spring 2020

# GRANT RECEIVED

Sage, A.J. (primary investigator), Del Toro, I., Oesper, L., Weinman, J., Exploring solutions for high performance computing at ACM institutions, Associated Colleges of the Midwest Faculty Career Enhancement grant, \$25,637 o Organized virtual workshop attended by 27 ACM faculty and staff (June 21-23, 2021)
