---
title: "Research"
format: html
editor: visual
---

My research interests include statistical learning, statistics education, applied statistical consulting, and sports analytics.

Statistical learning involves creating and evaluating predictive algorithms, designed to “learn” from and adapt to information contained in complex, noisy data. My research focuses on <a href="https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm"> random forest methodology </a>. My article <a href="https://www.tandfonline.com/doi/abs/10.1080/00031305.2022.2107568"> "From Black Box to Shining Spotlight" </a> introduces a set of web applications (<a href="https://predictive-visualizations.shinyapps.io/Prediction_Intervals_Simulation/">1</a>, <a href="https://predictive-visualizations.shinyapps.io/Prediction_Intervals_Real_Data/">2</a>) visualizing random forest prediction intervals and comparing them with intervals produced by linear regression models. I have also published articles introducing <a href="https://www.intlpress.com/site/pub/pages/journals/items/sii/content/vols/0014/0004/a003/"> a residual-based approach to robust random forest regression </a>, <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/sam.11446"> evaluating techniques for aggregating random forest predictions across trees </a>, and <a href="https://journals.sagepub.com/doi/abs/10.1177/1521025118780502"> using random forests to improve college student retention in STEM majors</a>.

I also enjoy working collaboratively with colleagues in the social and natural sciences. In 2025, I co-authored <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/eth.13545"> an article with Dr. Elizabeth Becker (a neuroscience) and her research team on pair bond formation in California mice  </a>, and another with <a href="https://link.springer.com/article/10.1007/s10862-025-10196-x"> Dr. Lori Hilt (a psychologist) and her research team on the effects of app-based mindfulness and mood monitoring strategies on the mental health of college students </a>. 

Finally, I enjoy applying statistical methods to sports data and have supervised several student projects in this area. One of these projects, by Derek Brickley, examined relationships between colleges' and universities' academic and athletic performances and <a href="https://www.siam.org/Portals/0/Publications/SIURO/Vol15/S149121.pdf?ver=2022-11-23-135316-360"> was published in SIAM Undergraduate Research Online in 2022</a>.

See my CV for a complete list of my peer-reviewed publications.   